### ISSUE TITLE
[BUG] Check for invalid flags starting with '-i'

### ISSUE THREAD

**Issue by Eakam1007** [devils2ndself/SSGo#5] opened 2022-09-16 23:20 UTC
I found that flags that begin with ```-i``` are accepted as if they are the input flag:

<img width="235" alt="image" src="https://user-images.githubusercontent.com/67077705/190829773-2b6c3dfc-dfdd-4447-9c00-5c944f39b46d.png">

**Comment by devils2ndself** [comment] 2022-09-21 01:58
Closing, as funnily enough this is not a bug, but a feature.  

Shorthand flags are intended to be exactly 1 ASCII character long, and everything that follows that character is supposed to be an input. See [this](https://github.com/spf13/pflag#command-line-flag-syntax) in the library's documentation.

**Closed as completed by devils2ndself** 2022-09-21 01:58 UTC
